name: .NET CI

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to main branch

jobs:
  build-and-test:
    runs-on: windows-latest  # Run the job on the latest Windows runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checks out the repository under $GITHUB_WORKSPACE

    - name: Setup .NET
      uses: actions/setup-dotnet@v4  # Set up .NET using the latest action version
      with:
        dotnet-version: '7.0.400'  # Specify .NET SDK version

    - name: Create TestResults Directory
      run: New-Item -Path "$GITHUB_WORKSPACE/TestResults" -ItemType Directory -Force
      shell: pwsh

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
          path: |
            ~/.nuget/packages
            !**/node_modules
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

    - name: Restore Dependencies
      run: dotnet restore
      # Run dotnet restore to restore the dependencies and tools of the project

    - name: Build and analyze code
      run: |
        dotnet build --no-restore --configuration Release /p:ReportOutputPath=${{ github.workspace }}/TestResults/AnalysisReport.html /p:ReportOutputFormat=html

    - name: Test with HTML report
      run: |
        dotnet test --no-build --verbosity normal --logger "html;LogFileName=${{ github.workspace }}/TestResults/test-results.html"

    - name: List output files
      run: ls ${{ github.workspace }}/TestResults

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: Test-Results
        path: ${{ github.workspace }}/TestResults/test-results.html

    - name: Upload analysis report
      uses: actions/upload-artifact@v2
      with:
        name: FxCop-Analysis-Report
        path: ${{ github.workspace }}/TestResults/AnalysisReport.html
